#ifndef ERRORS_H
#define ERRORS_H


#define ERROR_INVALID_PROGRAM_USAGE 1
#define ERROR_MEMORY_ALLOCATION_FAILURE 1
#define ERROR_INVALID_FUNCTION_PARAMETERS 1
#define ERROR_FATAL_FUNCTION_CALL 1



#endif // ERRORS_H